name: CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify notes.txt exists
        run: test -f notes.txt

      - name: Verify notes.txt is not empty
        run: test -s notes.txt
